/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 helmet.gltf --transform
Author: Arthur Krut (https://sketchfab.com/OptiCube)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/maximus-helmet-320c12145c8e42ddb89dd38fed3a5350
Title: Maximus Helmet
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/helmet-transformed.glb')
  return (
    <group {...props} dispose={null} >
      <group scale={0.8} position={[-5.7, 2, -1]} rotation={[0,-0.3,0]} >
        <group position={[0, -1.41, 0]}>
          <mesh geometry={nodes.polySurface4358_Feather_0.geometry} material={materials.Feather} />
          <mesh geometry={nodes.polySurface4358_Feather_Base_0.geometry} material={materials.Feather_Base} />
        </group>
        <group position={[0, -1.41, 0]}>
          <mesh geometry={nodes.polySurface6256_Feather_0.geometry} material={materials.Feather} />
          <mesh geometry={nodes.polySurface6256_Feather_Base_0.geometry} material={materials.Feather_Base} />
        </group>
        <group position={[0, -1.41, 0]}>
          <mesh geometry={nodes.polySurface4888_Feather_0.geometry} material={materials.Feather} />
          <mesh geometry={nodes.polySurface4888_Feather_Base_0.geometry} material={materials.Feather_Base} />
        </group>
        <group position={[0, -1.41, 0]}>
          <mesh geometry={nodes.polySurface6218_Feather_0.geometry} material={materials.Feather} />
          <mesh geometry={nodes.polySurface6218_Feather_Base_0.geometry} material={materials.Feather_Base} />
        </group>
        <group position={[0, -1.41, 0]}>
          <mesh geometry={nodes.polySurface5058_Feather_0.geometry} material={materials.Feather} />
          <mesh geometry={nodes.polySurface5058_Feather_Base_0.geometry} material={materials.Feather_Base} />
        </group>
        <group position={[0, -1.41, 0]}>
          <mesh geometry={nodes.polySurface4966_Feather_0.geometry} material={materials.Feather} />
          <mesh geometry={nodes.polySurface4966_Feather_Base_0.geometry} material={materials.Feather_Base} />
        </group>
        <mesh geometry={nodes.polySurface2207_Bolts_0.geometry} material={materials.Bolts} />
        <mesh geometry={nodes.polySurface2207_Bolts_0_1.geometry} material={materials.Bolts} />
        <mesh geometry={nodes.polySurface2207_Bolts_0_2.geometry} material={materials.Bolts} />
        <mesh geometry={nodes.polySurface2207_Bolts_0_3.geometry} material={materials.Bolts} />
        <mesh geometry={nodes.polySurface6_Leather_0.geometry} material={materials.Leather} />
        <mesh geometry={nodes.Main_Metal1_Main_Metal_0.geometry} material={materials.Main_Metal} />
        <mesh geometry={nodes.polySurface6269_Filter_0.geometry} material={materials.Filter} />
      </group>
    </group>
  )
}

useGLTF.preload('/helmet-transformed.glb')
