/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 home.gltf --transform
Author: Morrissey Alexander (https://sketchfab.com/reckzilla)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/japanese-residential-home-01-d690f83d8e8d48e6a532bebe84901595
Title: Japanese Residential Home 01
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/home-transformed.glb')
  return (
    <group {...props} dispose={null} scale={[0.004, 0.004, 0.004]} position={[0, -1, 0]} rotation={[0,-0.8,0]}>
      <mesh geometry={nodes.JapaneseResidentialHome_01_blinn1_0.geometry} material={materials.blinn1} />
    </group>
  )
}

useGLTF.preload('/home-transformed.glb')
