/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 lada.gltf --transform
Author: Nik (https://sketchfab.com/nikska)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/ancient-lada-2109-raw-f79bcdfc65804d2ab525bf893ba1e420
Title: Ancient Lada 2109 (RAW)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/lada-transformed.glb')
  return (
    <group {...props} dispose={null} scale={[0.18, 0.18, 0.18]}>
      <group rotation={[3.4, 3, 0.1]} >
        <mesh geometry={nodes.Object_2.geometry} material={materials.Lada_Model_6_u1_v1} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.Lada_Model_6_u1_v1} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.Lada_Model_6_u1_v1} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.Lada_Model_6_u1_v1} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.Lada_Model_6_u1_v1} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.Lada_Model_6_u1_v1} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.Lada_Model_6_u1_v1} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.Lada_Model_6_u1_v1} />
        <mesh geometry={nodes.Object_10.geometry} material={materials.Lada_Model_6_u1_v1} />
        <mesh geometry={nodes.Object_11.geometry} material={materials.Lada_Model_6_u1_v1} />
        <mesh geometry={nodes.Object_12.geometry} material={materials.Lada_Model_6_u1_v1} />
        <mesh geometry={nodes.Object_13.geometry} material={materials.Lada_Model_6_u1_v1} />
        <mesh geometry={nodes.Object_14.geometry} material={materials.Lada_Model_6_u1_v1} />
        <mesh geometry={nodes.Object_15.geometry} material={materials.Lada_Model_6_u1_v1} />
        <mesh geometry={nodes.Object_16.geometry} material={materials.Lada_Model_6_u1_v1} />
        <mesh geometry={nodes.Object_17.geometry} material={materials.Lada_Model_6_u1_v1} />
        <mesh geometry={nodes.Object_18.geometry} material={materials.Lada_Model_6_u1_v1} />
        <mesh geometry={nodes.Object_19.geometry} material={materials.Lada_Model_6_u1_v1} />
        <mesh geometry={nodes.Object_20.geometry} material={materials.Lada_Model_6_u1_v1} />
        <mesh geometry={nodes.Object_21.geometry} material={materials.Lada_Model_6_u1_v1} />
        <mesh geometry={nodes.Object_22.geometry} material={materials.Lada_Model_6_u1_v1} />
        <mesh geometry={nodes.Object_23.geometry} material={materials.Lada_Model_6_u1_v1} />
        <mesh geometry={nodes.Object_24.geometry} material={materials.Lada_Model_6_u1_v1} />
        <mesh geometry={nodes.Object_25.geometry} material={materials.Lada_Model_6_u1_v1} />
        <mesh geometry={nodes.Object_26.geometry} material={materials.Lada_Model_6_u1_v1} />
      </group>
    </group>
  )
}

useGLTF.preload('/lada-transformed.glb')
